INSERT INTO quiz(id_capitulo) VALUES
(1),
(2),
(3),
(4),
(5),
(6),
(7),
(8),
(9),
(10),
(11),
(12);

INSERT INTO pergunta(nome, texto, id_quiz, alternativa1, alternativa2, resposta_correta) VALUES
("Pergunta1", "O que Alice seguiu que a fez cair na toca?", 1, "Um coelho branco.", "Uma raposa.", "Um coelho branco."),
("Pergunta2", "Depois de cair na toca, Alice encontra um bolo com as palavras 'COMA-ME'. O que acontece com ela quando ela come o bolo?", 1, "Ela começa a crescer.", "Ela começa a diminuir.", "Ela começa a crescer."),
("Pergunta1", "O que aconteceu com Alice quando ela chorou muito?", 2, "Suas lágrimas formaram uma piscina enorme.", "Ela se afogou nas próprias lágrimas e foi salva por um peixe.", "Suas lágrimas formaram uma piscina enorme."),
("Pergunta2", "O que o Camundongo sentiu quando Alice falou sobre a gata Diná?", 2, "Raiva. Porque os camundongos têm medo e ódio de gatos.", "Alegria, porque também gostava de gatos.", "Raiva. Porque os camundongos têm medo e ódio de gatos."),
("Pergunta1", "Qual foi a ideia do Dodô para todo mundo se secar?", 3, "Fazer uma corrida maluca.", "Acender uma fogueira no meio do campo.", "Fazer uma corrida maluca."),
("Pergunta2", "Por que Alice ficou triste no final do capítulo?", 3, "Porque todos os bichos foram embora e ela ficou sozinha.", "Porque ela perdeu seu chapéu mágico.", "Porque todos os bichos foram embora e ela ficou sozinha."),
("Pergunta1", "O que Alice encontrou dentro da casa do Coelho Branco?", 4, "Ela encontrou o leque e as luvas.", "Um espelho encantado que falava.", "Ela encontrou o leque e as luvas."),
("Pergunta2", "Por que os animais chamaram o Bill de 'lagartixa-bala'?", 4, "Porque Alice deu um chute nele quando ele tentou descer pela chaminé, e Bill voou para fora da casa como se fosse uma bala disparada.", "Porque ele era o mais rápido de todos os animais.", "Porque Alice deu um chute nele quando ele tentou descer pela chaminé, e Bill voou para fora da casa como se fosse uma bala disparada."),
("Pergunta1", "O que a Taturana estava fazendo quando Alice a encontrou no topo do cogumelo?", 5, "Ela estava sentada fumando um narguilé.", "Dançando em cima do cogumelo.", "Ela estava sentada fumando um narguilé."),
("Pergunta2", "Qual foi a pergunta estranha que a Taturana fez para Alice?", 5, "'Quem é você?'", "'Você acredita em mágica?'", "'Quem é você?'"),
("Pergunta1", "O que tinha demais na sopa que fazia todo mundo espirrar?", 6, "Pimenta.", "Cebola crua.", "Pimenta."),
("Pergunta2", "O que aconteceu com a bebê depois que Alice saiu da casa da Duquesa?", 6, "A bebê virou uma porquinha.", "A bebê virou uma boneca de pano.", "A bebê virou uma porquinha."),
("Pergunta1", "Com quem Alice tomou chá?", 7, "Com a Lebre de Março, o Chapeleiro Maluco e a Preguiça.", "Com a Rainha de Copas, o Coelho Branco e o Dodô.", "Com a Lebre de Março, o Chapeleiro Maluco e a Preguiça."),
("Pergunta2", "Por que na mesa do chá era sempre cinco horas da tarde?", 7, "Porque o tempo brigou com o Chapeleiro, e desde então ficou sempre parado na hora do chá.", "Porque os relógios da casa estavam quebrados.", "Porque o tempo brigou com o Chapeleiro, e desde então ficou sempre parado na hora do chá."),
("Pergunta1", "Por que os jardineiros estavam pintando as rosas de vermelho?", 8, "Porque plantaram uma roseira branca por engano, e a Rainha só gostava de rosas vermelhas.", "Porque a Rainha gostava de fazer arte com flores coloridas.", "Porque plantaram uma roseira branca por engano, e a Rainha só gostava de rosas vermelhas."),
("Pergunta2", "O que eles usavam para os tacos e as bolas do jogo de croqué?", 8, "Os tacos eram flamingos e as bolas eram ouriços vivos.", "Tacos de madeira e bolas de borracha.", "Os tacos eram flamingos e as bolas eram ouriços vivos."),
("Pergunta1", "Quem levou Alice até o Jabuti de Mentira?", 9, "O Grifo.", "A Lebre de Março.", "O Grifo."),
("Pergunta2", "Quais eram as diferentes operações da aritmética que o Jabuti mencionou?", 9, "Ambição, distração, irrisão e enfeiamento.", "Soma, subtração, multiplicação e divisão.", "Ambição, distração, irrisão e enfeiamento."),
("Pergunta1", "O que era a Quadrilha das Lagostas?", 10, "Uma dança dos animais, junto com lagostas, depois jogavam as lagostas dentro d’água.", "Um jogo de cartas com lagostas mágicas.", "Uma dança dos animais, junto com lagostas, depois jogavam as lagostas dentro d’água."),
("Pergunta2", "O que os dançarinos faziam depois de jogar as lagostas para longe na água?", 10, "Nadavam atrás das lagostas e davam um mortal dentro da água.", "Voltavam para casa correndo.", "Nadavam atrás das lagostas e davam um mortal dentro da água."),
("Pergunta1", "Quem estava sendo acusado de ter roubado as tortas da Rainha de Copas?", 11, "O Valete de Copas.", "O Coelho Branco.", "O Valete de Copas."),
("Pergunta2", "Por que os jurados estavam escrevendo seus próprios nomes nas lousas antes mesmo do julgamento começar?", 11, "Porque tinham medo de esquecer os próprios nomes até o final da sessão.", "Porque estavam tentando copiar uns aos outros.", "Porque tinham medo de esquecer os próprios nomes até o final da sessão."),
("Pergunta1", "O que aconteceu quando Alice levantou-se de repente no tribunal?", 12, "Ela derrubou a banca do júri e espalhou os jurados.", "Ela foi transformada em uma estátua.", "Ela derrubou a banca do júri e espalhou os jurados."),
("Pergunta2", "Por que os jurados estavam escrevendo seus próprios nomes nas lousas antes mesmo do julgamento começar?", 12, "Elas se transformaram em folhas caindo, e Alice acordou.", "Elas viraram borboletas e desapareceram.", "Elas se transformaram em folhas caindo, e Alice acordou.");
